### ISSUE TITLE
The library won't connect to iFormBuilder - Unauthorized error

### ISSUE THREAD

**Issue by witness-me** [jhsu98/zerion-py#1]
I am trying to connect to iFormBuilder with the sample code provided in the example, but it returns an error. The client key and secret are 100% correct and I've tried different formats of server names such as 'https://test.iformbuilder.com/', 'test.iformbuilder.com', 'test' (as I understand the last format should be the right one).

Here's the code:
```
from zerionAPI import IFB
from secrets import server_name, client_secret, client_key

ifb = IFB(server_name, client_key, client_secret)
```
The console returns an error:
`Exception: 401 Client Error: Unauthorized for url: https://identity.zerionsoftware.com/oauth2/token`

Also, I've tried to use the `ifb-wrapper` library you created with the same variables (apart from the different format of server name) and the connection was successfully established there.

**Comment by jhsu98** [comment]
Hey Vlad, the issue is probably that you're using client key/secret from iform and not through ZIM. I didn't make clear that this uses ZIM as the authorization service and not iForm. Hence why the error has a url of `identity.zerionsoftware.com`. Let me work on a fix to use regular IFB API Apps. It'll be a params flag when creating the IFB object.

**Comment by witness-me** [comment]
You're right, I've got an iformbuilder's client credentials I'm trying to use for login.

Thank you for the reply, will be waiting for the update then!

**Comment by jhsu98** [comment]
@witness-me just pushed the change, version is now `0.0.5`. You'll need to update the zerionAPI package and then when you connect, include the optional params object with the key-value pair `ifb_api_credentials': True`

```python
IFB(server, ifb_client_key, ifb_client_secret, {'ifb_api_credentials': True})
```

**Comment by witness-me** [comment]
Wow, that was fast, thanks a million!
Just tried it, and it worked :)
